
package soen487.wscat.services.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSCATService", targetNamespace = "http://services.wscat.soen487/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSCATService {


    /**
     * 
     * @param repoURI
     * @return
     *     returns soen487.wscat.services.client.MarfcatIn
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "submitWSDLRepo", targetNamespace = "http://services.wscat.soen487/", className = "soen487.wscat.services.client.SubmitWSDLRepo")
    @ResponseWrapper(localName = "submitWSDLRepoResponse", targetNamespace = "http://services.wscat.soen487/", className = "soen487.wscat.services.client.SubmitWSDLRepoResponse")
    @Action(input = "http://services.wscat.soen487/WSCATService/submitWSDLRepoRequest", output = "http://services.wscat.soen487/WSCATService/submitWSDLRepoResponse")
    public MarfcatIn submitWSDLRepo(
        @WebParam(name = "repoURI", targetNamespace = "")
        String repoURI);

    /**
     * 
     * @param wsdlFile
     * @return
     *     returns java.lang.String
     * @throws InterruptedException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "submitWSDLToAnalyze", targetNamespace = "http://services.wscat.soen487/", className = "soen487.wscat.services.client.SubmitWSDLToAnalyze")
    @ResponseWrapper(localName = "submitWSDLToAnalyzeResponse", targetNamespace = "http://services.wscat.soen487/", className = "soen487.wscat.services.client.SubmitWSDLToAnalyzeResponse")
    @Action(input = "http://services.wscat.soen487/WSCATService/submitWSDLToAnalyzeRequest", output = "http://services.wscat.soen487/WSCATService/submitWSDLToAnalyzeResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://services.wscat.soen487/WSCATService/submitWSDLToAnalyze/Fault/IOException"),
        @FaultAction(className = InterruptedException_Exception.class, value = "http://services.wscat.soen487/WSCATService/submitWSDLToAnalyze/Fault/InterruptedException")
    })
    public String submitWSDLToAnalyze(
        @WebParam(name = "wsdlFile", targetNamespace = "")
        String wsdlFile)
        throws IOException_Exception, InterruptedException_Exception
    ;

    /**
     * 
     * @param wsdlFile
     * @param wsdlURI
     * @throws ParserConfigurationException_Exception
     * @throws SAXException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "trainOnFile", targetNamespace = "http://services.wscat.soen487/", className = "soen487.wscat.services.client.TrainOnFile")
    @ResponseWrapper(localName = "trainOnFileResponse", targetNamespace = "http://services.wscat.soen487/", className = "soen487.wscat.services.client.TrainOnFileResponse")
    @Action(input = "http://services.wscat.soen487/WSCATService/trainOnFileRequest", output = "http://services.wscat.soen487/WSCATService/trainOnFileResponse", fault = {
        @FaultAction(className = ParserConfigurationException_Exception.class, value = "http://services.wscat.soen487/WSCATService/trainOnFile/Fault/ParserConfigurationException"),
        @FaultAction(className = SAXException_Exception.class, value = "http://services.wscat.soen487/WSCATService/trainOnFile/Fault/SAXException"),
        @FaultAction(className = IOException_Exception.class, value = "http://services.wscat.soen487/WSCATService/trainOnFile/Fault/IOException")
    })
    public void trainOnFile(
        @WebParam(name = "wsdlFile", targetNamespace = "")
        String wsdlFile,
        @WebParam(name = "wsdlURI", targetNamespace = "")
        String wsdlURI)
        throws IOException_Exception, ParserConfigurationException_Exception, SAXException_Exception
    ;

}
